# Generated by Django 5.1.6 on 2025-03-10 10:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0002_recipe_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
